server:
  port: 20000
spring:
  application:
    # 应用名称
    name: gulimall-third-party
  profiles:
    # 环境配置
    active: dev
  cloud:
#阿里对象存储配置
    alicloud:
      access-key: ENC(XhNbMgeEkEuZHWMDkgyNwoHQDMEh55J2XdoxMx4ZhLW4EVbFvQVlDQ==)
      secret-key: ENC(ZtPMDu59je2MNeU0K8XbgwHyy/oSoLs+AWm9CVWWhMCvmMxg2g3+1A==)
      oss:
        endpoint: ENC(raEHM1sP+Vs+GQ/0qxIeFn/JelOZvmk74YkFOdx8cVpxg8sOPZLvlg==)
        bucket: ENC(W+Ka/rRDyC+Kwwv1fe7uHpRKIzZvUjcZlQeF9IuMopc=)
