server:
  port: 20000
spring:
  application:
    # 应用名称
    name: gulimall-third-party
  profiles:
    # 环境配置
    active: dev
  cloud:
#阿里对象存储配置
    alicloud:
      access-key: ENC(kFrPnG4GkXoHkB2I5PgeQ5ajS2WPLdm0g02+kMG3jJG0l4r70IOHSg==)
      secret-key: ENC(ZnHUsjHPF6SUbaguiJdpgeMCHCuZIPbCKr7LzgzOfvyc/OI+cFbX+A==)
      oss:
        endpoint: ENC(raEHM1sP+Vs+GQ/0qxIeFn/JelOZvmk74YkFOdx8cVpxg8sOPZLvlg==)
        bucket: ENC(W+Ka/rRDyC+Kwwv1fe7uHpRKIzZvUjcZlQeF9IuMopc=)
